from selenium.webdriver.support.select import Select
from selenium import webdriver
import time


driver = webdriver.Chrome("C:\\Users\\Bilal\\PycharmProjects\\TestAutomation\\Drivers\\chromedriver.exe")
driver.set_page_load_timeout(50)
driver.get("https://www.demo.iscripts.com/netmenus/mrml/")
driver.maximize_window()

driver.implicitly_wait(30)

driver.find_element_by_xpath("//a[contains(text(),'Log In')]").click()
time.sleep(5)
driver.find_element_by_xpath("//input[@id='txtUsername']").send_keys("aashu1130@outlook.com")
time.sleep(1)
driver.find_element_by_xpath("//input[@id='txtPassword']").send_keys("Minds123")
time.sleep(1)
driver.find_element_by_xpath("//input[@class='login_btn']").click()
time.sleep(2)
driver.find_element_by_xpath("//div[@class='col-md-6']//input[@id='search_keyword']").send_keys("CARAMEL")
time.sleep(2)
driver.find_element_by_xpath("//form[@id='frmSearch']//div[@class='col-md-12']//div//input[@id='Submit']").click()
driver.find_element_by_xpath("//a[@class='book_it']").click()
time.sleep(1)
driver.find_element_by_xpath("//li[@class='tab-current']//a[contains(text(),'Menu')]").click()
time.sleep(1)
driver.find_element_by_xpath("//a[@class='basic']//img").click()
driver.find_element_by_xpath("//div[@id='fade_206_541']//textarea[@id='special_request']").send_keys("Deliver the order as soon as possible")
time.sleep(1)
driver.find_element_by_xpath("//div[@id='fade_206_541']//div[@id='divskip']").click()
time.sleep(2)
driver.find_element_by_xpath("//a[@class='jQAddFoodItem']//img").click()
time.sleep(2)
driver.find_element_by_xpath("//a[@class='jQAddFoodItem']//img").click()
time.sleep(2)
driver.find_element_by_xpath("//a[@id='jQOrderFn']").click()
time.sleep(1)
driver.find_element_by_xpath("//span[contains(text(),'Orders')]").click()
time.sleep(1)
obj=Select(driver.find_element_by_xpath("//select[@id='tippercent']"))
time.sleep(1)
obj.select_by_value("25")
time.sleep(1)
driver.find_element_by_xpath("//input[@name='btnCheckout']").click()
time.sleep(1)
driver.find_element_by_xpath("//form[@id='frmcheckout']//input[@placeholder='First Name*']").clear()
time.sleep(1)
driver.find_element_by_xpath("//form[@id='frmcheckout']//input[@placeholder='First Name*']").send_keys("Syed")
time.sleep(1)
driver.find_element_by_xpath("//form[@id='frmcheckout']//input[@placeholder='Last Name*']").clear()
time.sleep(1)
driver.find_element_by_xpath("//form[@id='frmcheckout']//input[@placeholder='Last Name*']").send_keys("Bilal")
time.sleep(1)
driver.find_element_by_xpath("//form[@id='frmcheckout']//input[@placeholder='Email*']").clear()
time.sleep(1)
driver.find_element_by_xpath("//form[@id='frmcheckout']//input[@placeholder='Email*']").send_keys("syed.bilal005@gmail.com")
time.sleep(1)
driver.find_element_by_xpath("//form[@id='frmcheckout']//input[@placeholder='Address line 1*']").send_keys("HIGHCOURT,GULBARGA")
time.sleep(1)
driver.find_element_by_xpath("//form[@id='frmcheckout']//input[@placeholder='Address line 2*']").send_keys("IT.PARK")
time.sleep(1)
driver.find_element_by_xpath("//form[@id='frmcheckout']//input[@placeholder='City*']").send_keys("GULBARGA")
time.sleep(1)
obj=Select(driver.find_element_by_xpath("//select[@id='billCountrySelect']"))
time.sleep(1)
obj.select_by_value("IN")
time.sleep(1)
driver.find_element_by_xpath("//form[@id='frmcheckout']//input[@placeholder='ZIP*']").send_keys("585101")
time.sleep(1)
driver.find_element_by_xpath("//input[@id='billStateSelect']").send_keys("KARNATAKA")
time.sleep(1)
driver.find_element_by_xpath("//form[@id='frmcheckout']//input[@placeholder='Phone*']").send_keys("9988776655")
time.sleep(1)
driver.find_element_by_xpath("//input[@id='same_as_billing']").click()
time.sleep(1)
driver.find_element_by_xpath("//input[@name='btnCheckout']").click()
time.sleep(2)
driver.find_element_by_xpath("//input[@name='btnOrder']").click()
time.sleep(1)
driver.get_screenshot_as_file("E:\\screenshot\\ofos.png")
time.sleep(2)
driver.find_element_by_xpath("//a[contains(text(),'Back to Home')]").click()
time.sleep(1)
driver.find_element_by_xpath("//a[contains(text(),'Log Out')]").click()
time.sleep(1)
driver.quit()
